all: Assign2_Processes Assign2_Threads

Assign2_Processes: Assign2_Processes.cpp
	g++ Assign2_Processes.cpp -pthread -o Assign2_Processes

Assign2_Threads: Assign2_Threads.cpp
	g++ Assign2_Threads.cpp -pthread -o Assign2_Threads
