all: Assign3_Part1 Assign3_Composite

Assign3_Part1: Assign3_Part1.cpp
	g++ Assign3_Part1.cpp -pthread -o Assign3_Part1

Assign3_Composite: Assign3_Composite.cpp
	g++ Assign3_Composite.cpp -pthread -o Assign3_Composite
